# Generated by Django 5.1.2 on 2024-11-02 02:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_address_profile_avatar_profile_bio_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profil", "verbose_name_plural": "Profils"},
        ),
    ]
