# Generated by Django 4.2.17 on 2024-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0001_initial"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="beneficiere",
            field=models.ManyToManyField(
                blank=True, null=True, to="section.beneficiere"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="source",
            field=models.ManyToManyField(blank=True, null=True, to="section.etudiant"),
        ),
    ]
