# Generated by Django 4.2.17 on 2024-12-09 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("section", "0001_initial"),
        ("finance", "0002_transaction_beneficiere_transaction_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="beneficiere",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="source",
        ),
        migrations.AddField(
            model_name="transaction",
            name="beneficiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="section.beneficiere",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="section.etudiant",
            ),
        ),
    ]
