# Generated by Django 4.2.17 on 2024-12-11 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_remove_transaction_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="etatbesoin",
            name="budget",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.budget",
            ),
            preserve_default=False,
        ),
    ]
